version: '3.1'
services:
  nmcp-db:
    image: postgres:16
    hostname: nmcp-db
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "${DATABASE_PW}"
    volumes:
      - data:/var/lib/postgresql/data
      - ./datastore/nmcp:/docker-entrypoint-initdb.d
    networks:
      - back_tier

volumes:
  data:

networks:
  back_tier:
