# Services that will be run regardless of environment and will not be built locally as part of development.
services:
  db:
    image: postgres:18
    hostname: nmcp-db
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "${NMCP_DATABASE_PW}"
    volumes:
      - data:/var/lib/postgresql/data
      - ./datastore/nmcp:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back_tier
    restart: unless-stopped

  influxdb:
    image: influxdb:2
    hostname: nmcp-influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: "${NMCP_INFLUX_DB_PASSWORD}"
      DOCKER_INFLUXDB_INIT_ORG: nmcp
      DOCKER_INFLUXDB_INIT_BUCKET: nmcp
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - back_tier
    restart: unless-stopped

volumes:
  data:
  influxdb_data:

networks:
  back_tier:
