# Services that are required, but which may be run outside of containers as part of development, etc.  Starting container versions of these services is
# optional under those conditions.
#
# This is a convenience file for running the latest images for each container as part of a staging or internal deployment phase.  For production deployments
# see docker-compose.services.yml.
services:
  api:
    image: leapscientific/nmcp-api:2.0.37
    hostname: nmcp-api
    environment:
      NODE_ENV: production
      NMCP_EXPERIMENTAL_ENV: true
      NMCP_CCF_30_ONTOLOGY_PATH: "${NMCP_ONTOLOGY_PATH}"
      NMCP_AUTH_REQUIRED: true
      NMCP_AUTHENTICATION_KEY: "${NMCP_AUTH_CLIENT_ID}"
      NMCP_AUTHENTICATION_CLIENT_ID: "${NMCP_AUTHENTICATION_CLIENT_ID}"
      NMCP_DATABASE_PW: "${NMCP_DATABASE_PW}"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
      - "${NMCP_ONTOLOGY_LOCATION}:${NMCP_ONTOLOGY_LOCATION}"
    ports:
      - "9671:5000"
    networks:
      - back_tier
    restart: unless-stopped

  client:
    image: leapscientific/nmcp-client:2.0.32
    hostname: nmcp-client
    environment:
      NODE_ENV: production
      NMCP_API_HOST: nmcp-api
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
    ports:
      - "9693:5000"
    networks:
      - back_tier
    restart: unless-stopped

  export:
    image: leapscientific/nmcp-export:2.0.4
    hostname: nmcp-export
    environment:
      NODE_ENV: production
      NMCP_AUTHENTICATION_KEY: "${NMCP_AUTH_CLIENT_ID}"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
    ports:
      - "9692:5000"
    networks:
      - back_tier
    restart: unless-stopped

  static-api:
    image: leapscientific/nmcp-static-resources:2.0.0
    hostname: nmcp-static
    environment:
      NODE_ENV: production
      STATIC_API_IS_INTERNAL: 1
      STATIC_SLICE_MOUNT_POINT: "/data/slice/"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
      - "${NMCP_SLICE_LOCATION}:/data/slice"
    ports:
      - "9691:5000"
    networks:
      - back_tier
    restart: unless-stopped

  precomputed-worker:
    image: leapscientific/nmcp-precomputed-worker:1.0.7
    hostname: precomputed-worker
    environment:
      GRAPHQL_URL: http://nmcp-api:5000/graphql
      SERVER_AUTHENTICATION_KEY: "${NMCP_AUTH_CLIENT_ID}"
      PRECOMPUTED_OUTPUT: "${NMCP_PRECOMPUTED_OUTPUT}"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
      - "${NMCP_SECRETS_VOLUME}:/root/.cloudvolume/secrets"
    networks:
      - back_tier
    restart: unless-stopped

volumes:
  log_output:

networks:
  back_tier:
