# Services that will be run regardless of environment and will not be built locally as part of development.
services:
  db:
    image: postgres:16
    hostname: nmcp-db
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "${NMCP_DATABASE_PW}"
    volumes:
      - data:/var/lib/postgresql/data
      - ./datastore/nmcp:/docker-entrypoint-initdb.d
    networks:
      - back_tier

volumes:
  data:

networks:
  back_tier:
