# Services that are required, but which may be run outside of containers as part of development, etc.  Starting container versions of these services is
# optional under those conditions.
#
# Image versions in this file are the current, stable, production-ready images, which may not correspond to "latest" or version-less image names.
services:
  api:
    image: ghcr.io/allenneuraldynamics/nmcp-api:3.0.15
    hostname: nmcp-api
    environment:
      NODE_ENV: production
      NMCP_CCF_30_ONTOLOGY_PATH: "${NMCP_ONTOLOGY_PATH}"
      NMCP_AUTH_REQUIRED: true
      NMCP_SERVER_KEY: "${NMCP_SERVER_KEY}"
      NMCP_AUTHENTICATION_API_APP_ID: "${NMCP_AUTHENTICATION_API_APP_ID}"
      NMCP_AUTHENTICATION_TENANT_ID: "${NMCP_AUTHENTICATION_TENANT_ID}"
      NMCP_DATABASE_PW: "${NMCP_DATABASE_PW}"
      NMCP_INFLUX_DB_TOKEN: "${NMCP_INFLUX_DB_TOKEN}"
      NMCP_DOI_API_URL: "${NMCP_DOI_URL}"
      NMCP_DOI_API_HOST: "${NMCP_DOI_HOST}"
      NMCP_DOI_API_PREFIX: "${NMCP_DOI_PREFIX}"
      NMCP_DOI_API_USER: "${NMCP_DOI_USER}"
      NMCP_DOI_API_PASSWORD: "${NMCP_DOI_PASSWORD}"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
      - "${NMCP_ONTOLOGY_LOCATION}:${NMCP_ONTOLOGY_LOCATION}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    ports:
      - "9671:5000"
    networks:
      - back_tier
    restart: unless-stopped

  client:
    image: ghcr.io/allenneuraldynamics/nmcp-client:3.0.15
    hostname: nmcp-client
    environment:
      NODE_ENV: production
      NMCP_API_HOST: nmcp-api
      NMCP_PRECOMPUTED_OUTPUT: "${NMCP_PRECOMPUTED_OUTPUT}"
      NMCP_GOOGLE_ANALYTICS_TAG: "${NMCP_GOOGLE_ANALYTICS_TAG}"
      NMCP_DOI_HANDLER: "${NMCP_DOI_HANDLER}"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "9693:5000"
    networks:
      - back_tier
    restart: unless-stopped

  export:
    image: ghcr.io/allenneuraldynamics/nmcp-export:3.0.6
    hostname: nmcp-export
    environment:
      NODE_ENV: production
      NMCP_AUTHENTICATION_KEY: "${NMCP_SERVER_KEY}"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "9692:5000"
    networks:
      - back_tier
    restart: unless-stopped

  precomputed-worker:
    image: ghcr.io/allenneuraldynamics/nmcp-precomputed-worker:3.0.5
    hostname: precomputed-worker
    environment:
      GRAPHQL_URL: http://nmcp-api:5000/graphql
      SERVER_AUTHENTICATION_KEY: "${NMCP_SERVER_KEY}"
      PRECOMPUTED_OUTPUT: "${NMCP_PRECOMPUTED_OUTPUT}"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - back_tier
    restart: unless-stopped

  quality-api:
    image: ghcr.io/allenneuraldynamics/nmcp-qc:3.0.3
    hostname: quality-api
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "9694:5000"
    volumes:
      - "${NMCP_LOG_VOLUME}:/var/log/nmcp"
    networks:
      - back_tier
    restart: unless-stopped

volumes:
  log_output:

networks:
  back_tier:
